# EIGN: A universal model for edge-level problems

Here, we will show you how to use the EIGN model for edge-level problems on a dummy graph.

In [6]:
import os
import sys
import torch

# Add the 'scripts' directory to Python Path
scripts_path = os.path.abspath(os.path.join(os.getcwd(), ".."))
if scripts_path not in sys.path:
    sys.path.append(scripts_path)

from gnn.models import EIGNLaplacianConv

### Create a dummy graph

Let's create a dummy graph with some directed and undirected edges. We assign each edge with features that have an inherent direction (signed or orientation equivariant features) and some features that do not have an inherent direction (unsigned or orientation invariant features).

The signed features are represented with respect to some arbitrary edge orientation through their sign. The edge orientation is encoded through the `edge_index`: If it contains an edge `(u, v)`, signed features are represented relative to the orientation `u -> v`.


In [11]:
num_signed_features = 3
num_unsigned_features = 6

# Represent the graph
edge_index = (
    torch.tensor(
        [
            [0, 1],
            [1, 2],
            [2, 3],
            [2, 4],
            [3, 5],
            [5, 0],
            [5, 2],
        ]
    )
    .t()
    .contiguous()
)
edge_is_directed = torch.tensor([0, 0, 0, 0, 0, 1, 1], dtype=torch.bool)

dummy_features_signed = torch.randn(edge_index.size(1), num_signed_features)
dummy_features_unsigned = torch.randn(edge_index.size(1), num_unsigned_features)

print("edge_index shape: ", edge_index.shape)
print("edge_is_directed shape: ", edge_is_directed.shape)
print("dummy_features_signed shape: ", dummy_features_signed.shape)
print("dummy_features_unsigned shape: ", dummy_features_unsigned.shape)

edge_index shape:  torch.Size([2, 7])
edge_is_directed shape:  torch.Size([7])
dummy_features_signed shape:  torch.Size([7, 3])
dummy_features_unsigned shape:  torch.Size([7, 6])


### Create the basic EIGN model

We can create an instance of EIGN easily using the `eign` package. It produces both signed outputs (w.r.t. edge orientation) and unsigned outputs.

In [8]:
model = EIGNLaplacianConv(
    in_channels_signed=num_signed_features,
    in_channels_unsigned=num_unsigned_features,
    hidden_channels_signed=32,
    hidden_channels_unsigned=32,
    out_channels_signed=1,
    out_channels_unsigned=5,
    num_blocks=4,
    q=1 / edge_index.size(1),
).eval()

In [10]:
# Ensure edge_index is in the correct shape (2, num_edges)
if edge_index.dim() != 2 or edge_index.size(0) != 2:
    raise ValueError("edge_index must have shape [2, num_edges]")

# Ensure feature tensors match the expected dimensions
if dummy_features_signed.size(1) != num_signed_features:
    raise ValueError("dummy_features_signed must have the correct number of signed features")
if dummy_features_unsigned.size(1) != num_unsigned_features:
    raise ValueError("dummy_features_unsigned must have the correct number of unsigned features")

with torch.no_grad():
    outputs = model(
        x_signed=dummy_features_signed,
        x_unsigned=dummy_features_unsigned,
        edge_index=edge_index,
        is_directed=edge_is_directed,
    )
outputs.signed, outputs.unsigned

RuntimeError: The size of tensor a (32) must match the size of tensor b (2) at non-singleton dimension 2

### Verify Orientation Equivariance and Invariance

If we change the orientation of *undirected* edges, EIGN's outputs do not change.

In [5]:
# Flip the orientation of edges 2 and 4
orientation_flipped = torch.zeros(edge_index.size(1), dtype=torch.bool)
orientation_flipped[2] = 1
orientation_flipped[4] = 1

edge_index_flipped = edge_index.clone()
edge_index_flipped[:, orientation_flipped] = edge_index_flipped.flip(0)[
    :, orientation_flipped
]

# Represent signed features in this new orientation
dummy_features_signed_flipped = dummy_features_signed.clone()
dummy_features_signed_flipped[orientation_flipped] = -dummy_features_signed_flipped[
    orientation_flipped
]

with torch.no_grad():
    outputs_flipped = model(
        x_signed=dummy_features_signed_flipped,
        x_unsigned=dummy_features_unsigned,
        edge_index=edge_index_flipped,
        is_directed=edge_is_directed,
    )

Unsigned signals which are not represented relative to an orientation remain unchanged.

In [6]:
outputs_flipped.unsigned - outputs.unsigned

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Signed outputs also are not changed. However, since we changed the orientation of some edges, the sign of the corresponding signed signals have flipped. Intuitively, we have changed the basis in which signed signals are represented. This change is reflected through the sign in both EIGN's inputs and outputs.

In [7]:
# The signed outputs did not change as well, but are represented w.r.t. the new orientation
outputs_flipped_signed_old_orientation = outputs_flipped.signed.clone()
# If we reorient them back into the old orientation ...
outputs_flipped_signed_old_orientation[
    orientation_flipped
] = -outputs_flipped_signed_old_orientation[orientation_flipped]
# ... we get the same values
outputs_flipped_signed_old_orientation - outputs.signed

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

However, if we change the orientation (=direction) of a *directed* edge, EIGN is sensitive to that and outputs different signed and unsigned features. It can therefore learn to model the direction of directed edges and still represent signed and unsigned edge signals.

In [8]:
# Change the orientation of a directed edge
orientation_flipped_directed = torch.zeros(edge_index.size(1), dtype=torch.bool)
orientation_flipped_directed[5] = 1

edge_index_flipped_directed = edge_index.clone()
edge_index_flipped_directed[:, orientation_flipped_directed] = (
    edge_index_flipped_directed.flip(0)[:, orientation_flipped_directed]
)
edge_index

tensor([[0, 1, 2, 2, 3, 5, 5],
        [1, 2, 3, 4, 5, 0, 2]])

In [9]:
# Represent signed features in this new orientation

dummy_features_signed_flipped_directed = dummy_features_signed.clone()
dummy_features_signed_flipped_directed[
    orientation_flipped_directed
] = -dummy_features_signed_flipped_directed[orientation_flipped_directed]

with torch.no_grad():
    outputs_flipped_directed = model(
        x_signed=dummy_features_signed_flipped_directed,
        x_unsigned=dummy_features_unsigned,
        edge_index=edge_index_flipped_directed,
        is_directed=edge_is_directed,
    )

In [10]:
# Now, the change in orientation (i.e. direction) of the edge breaks orientation invariance ...
outputs.unsigned - outputs_flipped_directed.unsigned

tensor([[-0.0022,  0.0014, -0.0029, -0.0051,  0.0263],
        [-0.0009, -0.0099,  0.0009, -0.0038, -0.0015],
        [ 0.0061, -0.0016, -0.0139, -0.0135,  0.0121],
        [ 0.0026, -0.0069, -0.0062, -0.0020,  0.0078],
        [-0.0063,  0.0072,  0.0134,  0.0095,  0.0028],
        [ 0.0244, -0.0085, -0.0058, -0.0036,  0.0286],
        [-0.0077, -0.0124, -0.0079,  0.0314, -0.0016]])

In [11]:
# ... and also orientation equivariance (w.r.t the old orientation)
outputs_flipped_directed_old_orientation = outputs_flipped_directed.signed.clone()
outputs_flipped_directed_old_orientation[
    orientation_flipped_directed
] = -outputs_flipped_directed_old_orientation[orientation_flipped_directed]
outputs_flipped_directed_old_orientation - outputs.signed

tensor([[ 0.0093],
        [ 0.0012],
        [-0.0027],
        [-0.0037],
        [ 0.0407],
        [ 0.1137],
        [-0.0196]])

### Different variations of EIGN

EIGN's Magnetic Laplacian operators also allow representing edge signals at the node level which further increases its expressivity (see our [paper](https://arxiv.org/pdf/2410.16935) for further reading).

In [12]:
model = EIGNLaplacianWithNodeTransformationConv(
    in_channels_signed=num_signed_features,
    in_channels_unsigned=num_unsigned_features,
    hidden_channels_signed=32,
    hidden_channels_unsigned=32,
    out_channels_signed=1,
    out_channels_unsigned=5,
    num_blocks=4,
    q=1 / edge_index.size(1),
).eval()

You can even define your own (learnable) mapping to transform node features that are induced by the Magnetic Edge Laplacian's boundary operators. By default, a `ReLU` is used to introduce some nonlinearity. You can use whatever you want, even a node-level GNN is possible here.

In [13]:
def initialize_node_feature_transformation(
    num_channels_in: int, num_channels_out: int
) -> nn.Module:
    return nn.Sequential(
        nn.ReLU(),
        nn.Linear(num_channels_in, num_channels_out),
        nn.ReLU(),
        nn.Linear(num_channels_out, num_channels_out),
    )


model = EIGNLaplacianWithNodeTransformationConv(
    in_channels_signed=num_signed_features,
    in_channels_unsigned=num_unsigned_features,
    hidden_channels_signed=32,
    hidden_channels_unsigned=32,
    out_channels_signed=1,
    out_channels_unsigned=5,
    num_blocks=4,
    q=1 / edge_index.size(1),
    initialize_node_feature_transformation=initialize_node_feature_transformation,
).eval()